name: Build & Push Docker Images

on:
  push:
    branches: [ "master", "feature/cicd" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master", "feature/cicd" ]

env:
  MF_DOCKER_IMAGE_NAME_PREFIX: mainfluxlabs

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Formatting
        run: go fmt ./...

      - name: Run go vet
        run: go vet -mod=vendor -tags nats ./...
      
      - name: Run Go tests
        run: go test ./...

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT
          fi
      
      - name: Build and push Docker images
        run: |
          make dockers \
            VERSION=${{ steps.version.outputs.version }} \
            COMMIT=${GITHUB_SHA} \
            TIME=$(date +%F_%T)
