name: Build & Push Docker Images

on:
  push:
    branches: [ "master", "feature/cicd" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master", "feature/cicd" ]

env:
  MF_DOCKER_IMAGE_NAME_PREFIX: mainfluxlabs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Auto-format Go code
        run: go fmt ./...

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-format code with go fmt"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com

      - name: Run go vet
        run: go vet -mod=vendor -tags nats ./...
      
      - name: Run Go tests
        run: make test

      - name: Set VERSION from Git tag or commit
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git describe --tags --abbrev=0 2>/dev/null)
            VERSION="${VERSION}-${GITHUB_SHA::7}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building version: ${VERSION}"
      
      - name: Build Docker images
        run: |
          make dockers \
            VERSION=${{ steps.version.outputs.version }} \
            COMMIT=${GITHUB_SHA} \
            TIME=$(date +%F_%T)
